### ISSUE TITLE
Support for Godot 4 (pls ^^)

### ISSUE THREAD

**Issue by SchimmelSpreu83** [2nafish117/godot-verlet-rope#3]
This addon is awesome, unfortunately I'm developing a project on Godot 4 and therefore can't use this addon like in G3.
When I tried to fix the problems and attached an end point to the rope, Godot just crashes.

I have no idea what to do further, so if you want, you could (re-)make it for G4! It would help a lot of people out ^^

**Comment by 2nafish117** [comment]
I plan to at some point convert this to a gdextension plugin for godot 4, but havent got the time. But here is WIP godot 4 port of this plugin, check out the 4.0 branch https://github.com/V-Sekai/godot-verlet-rope.

**Comment by ghost** [comment]
hey man, this plugin is really sick. did you update this to Godot 4? i've seen nothing like it before in godot!

**Comment by 2nafish117** [comment]
I suggest anyone looking for a 4.x version of this plugin to check out https://github.com/Tshmofen/verlet-rope-4, it is a well made port of this plugin to godot 4.x.
I will no longer be updating this plugin much.
