### ISSUE TITLE
issue on Godot_v4.3

### ISSUE THREAD

**Issue by Shawn-Akii** [2nafish117/godot-verlet-rope#6]
![螢幕擷取畫面 2024-09-01 223720](https://github.com/user-attachments/assets/c49f93ce-ee8d-439e-b2bc-0fac7c862e0b)
About FAQ Addon is throwing errors when I'm trying to enable it, what should I do?
I tried solution below,but the issue stil exit,my godot version is Godot_v4.3-stable_mono_win64

**Comment by 2nafish117** [comment]
Looks like you're using the 4.x version of the plugin, i suggest you ask this question on https://github.com/Tshmofen/verlet-rope-4 because that's the version you are using.
This repo is only maintained for the 3.x version of the plugin.
